### PR TITLE
Remove loop=loop in asyncio.wait call. Fix #245

### LINKED ISSUE #245: asyncio.wait() no longer accepts the loop keyword in Python 3.10
Hello. The code in here:

https://github.com/jupyter/jupyter_console/blob/64f1695d7efbc60d29b98e652b3d71fb9227eb07/jupyter_console/ptshell.py#L664

Fails with this on Python 3.10:

```
$ jupyter-console 
Jupyter console 6.4.0

Python 3.10.0b3 (default, Jun 17 2021, 00:00:00) [GCC 11.1.1 20210617 (Red Hat 11.1.1-5)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.24.1 -- An enhanced Interactive Python. Type '?' for help.
Traceback (most recent call last):
  File "/usr/bin/jupyter-console", line 33, in <module>
    sys.exit(load_entry_point('jupyter-console==6.4.0', 'console_scripts', 'jupyter-console')())
  File "/usr/lib/python3.10/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.10/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/usr/lib/python3.10/site-packages/jupyter_console/app.py", line 148, in start
    self.shell.mainloop()
  File "/usr/lib/python3.10/site-packages/jupyter_console/ptshell.py", line 664, in mainloop
    main_task = asyncio.wait(tasks, loop=loop, return_when=asyncio.FIRST_COMPLETED)
TypeError: wait() got an unexpected keyword argument 'loop'
sys:1: RuntimeWarning: coroutine 'ZMQTerminalInteractiveShell.interact' was never awaited
<mock-chroot> sh-5.1$ [IPKernelApp] WARNING | Parent appears to have exited, shutting down.
^C
```

The issue is that asyncio.wait() no longer accepts the loop keyword in python 3.10; see https://docs.python.org/3.10/library/asyncio-task.html#waiting-primitives.

### PR DESCRIPTION
**Pull request by lf-**
Fixes #245

### CODE REVIEW

**Comment by amerlyq** [comment]
@This PR

**Comment by lf-** [comment]
That's absolutely bizarre. The implication of run_in_executor further up in that stack is that there is in fact a current event loop, so I really don't know what the issue is. Can someone else help?

**Comment by NeilGirdhar** [comment]
@tinmarino Any ideas?

**Comment by tinmarino** [comment]
@NeilGirdhar sry no idea, no time to investigate. It seems that the thread registration has changed. To troubleshoot, see if removing the await keyword works. In that case, maybe divide this line in 2: `await loop.run_in_executor`.
Sry <= in southern summer break

**Comment by NeilGirdhar** [comment]
@tinmarino Thank you very much for the pointers!  Very kind of you.  Sorry if my ping was an imposition.  I just saw you as the last person to touch these lines. :smile:

**Comment by tinmarino** [comment]
@NeilGirdhar that was fast ! Do not worry, I am actually glad (proud) you called for my point of view 😎.
Gracias desde Chile 🐧

**Comment by ahesford** [comment]
I don't use jupyter for anything, but we're looking at this patch for Void Linux in https://github.com/void-linux/void-packages/pull/35376. Looking very narrowly, this seems to be wrong because `loop = asyncio.get_event_loop()` will cause the creation of an event loop when called outside of the event loop itself. Prior to Python 3.7, the `asyncio.wait(..., loop=loop, ...)` call would properly wait within the created event loop. Since 3.8, however, this has been ignored and the `wait` attempts to run in the current event loop if that exists; I don't know what happens when called outside an event loop (cf. https://docs.python.org/3/library/asyncio-task.html#waiting-primitives). Obviously, with Python 3.10, the interface breaks and this triggers an obvious failure.

Note that `loop.run_in_executor` may imply that an event loop exists, but the call being run within the executor isn't an async coroutine function but a normal synchronous function (cf. https://docs.python.org/3/library/asyncio-eventloop.html#executing-code-in-thread-or-process-pools) and is probably *not* aware of an existing asyncio event loop because it isn't running in that context---it is running in an entirely different thread.

I suspect the right fix here is to move the body of the `while` loop into its own async coroutine function so you can do
```python
loop = asyncio.get_event_loop()
while True:
    loop.run_until_complete(self.do_loop_body())
```
or something to that effect. This will allow things like `asyncio.wait` to run in the proper event loop.

**Comment by davidbrochart** [comment]
Sorry @lf-, I didn't see this PR and I merged the change in #264. Thanks anyway!

**Comment by amerlyq** [comment]
@davidbrochart 
> With c.ZMQTerminalInteractiveShell.include_other_output = True it still crashes:

I was able to dirty-fix that by
```python
    async def handle_external_iopub(self, loop=None):
        while self.keep_running:
            # we need to check for keep_running from time to time as
            # we are blocking in an executor block which cannot be cancelled.
            # poll_result = await loop.run_in_executor(
            #     None, self.client.iopub_channel.socket.poll, 500)
            poll_result = await self.client.iopub_channel.socket.poll(500)
            if poll_result:
                self.handle_iopub()
```
Looks like run_in_executor() uses threadpool by default, and none of its threads have eventloop initialized.
Therefore .poll() fails, as Jupyter started to depend on eventloop from some time ago.
Not sure if it's proper, but at least it works.

**Pull request closed without merging**
