### PR TITLE
Fix import of cast_unicode_py2

### LINKED ISSUE #198: "cannot import name cast_unicode_py2" from ptshell.py
Because of jupyter_console/ptshell.py line 22, I was unable to start the coconut --ipython console.
In order to succeed, I changed the file as follows:
```python
from IPython.utils.py3compat import input
from ipython_genutils.py3compat import cast_unicode_py2
```

### PR DESCRIPTION
**Pull request by dylanfprice**
Fixes #198. I have verified that after making this change in a local venv I can run jupyter-console again.

### CODE REVIEW

**Comment by bentilley** [comment]
I also hit up against this error just now. I got it working with:
```
from ipython_genutils.py3compat import cast_unicode_py2, input
```
...changing the import for both to the genutils lib. Possibly tidier to import them both from the same place to save on import bloat 🤷‍♀ 

Can verify @dylanfprice 's fix though, so either way looks good to merge 👍

**Comment by QuLogic** [comment]
As mentioned in the [related issue](https://github.com/jupyter/jupyter_console/issues/198#issuecomment-570735168), `cast_unicode_py2` does nothing, and since Jupyter console doesn't support Python 2, I think it's better to remove those calls and the import entirely.

**Comment by QuLogic** [comment]
Actually, I found more Python 2 things to remove, so I opened a PR myself.

**Comment by dylanfprice** [comment]
Closed in favor of #201!

**Pull request closed without merging**
