### PR TITLE
Correct jupyter_console package name in readme

### PR DESCRIPTION
**Pull request by TerrorJack**

### CODE REVIEW

**Comment by dsblank** [comment]
Either name version works, correct?

**Comment by TerrorJack** [comment]
Haven't tried `pip`, but `conda` only accepts `jupyter_console`.

**Comment by cdgreenidge** [comment]
This should be fixed, `jupyter-console` does not work for conda.

**Comment by phil-blain** [comment]
Hi !  noticed the installation doc at https://jupyter-console.readthedocs.io/en/latest/ still mentions `jupyter-console` as the conda package name, I guess because read-the-docs shows the docs for the latest _released_ version. Have you considered enabling read-the-docs for the `master` branch ? This way these kind of corrections immediately make their way to the online documentation.

**Pull request merged**
