### PR TITLE
Async prompt for real time update from other clients

### PR DESCRIPTION
**Pull request by wendazhou**
Hi,

Contributing for the first time for a scenario that would be very useful for me.
By using `prompt_toolkit` async capabilities, we can display outputs from other clients in realtime when `include_other_output` is true (without having to refresh the console).

Unfortunately this requires python >= 3.3 for `asyncio`. If support for python 2.7 is required, how would you feel about conditionally enabling this feature? (there would probably be some more code).

demo

### CODE REVIEW

**Comment by takluyver** [comment]
Nice, thanks! We are still supporting Python 2.7 at the moment, but I'd be open to making version 6.0 require Python 3 (cc @Carreau @minrk ).

**Comment by minrk** [comment]
>  I'd be open to making version 6.0 require Python 3 (cc @Carreau @minrk ).

👍  Make sure we set the right Requires-Python, and :shipit:

**Comment by wmvanvliet** [comment]
This is really cool! Any chance of digging this thing back up?

**Comment by rgbkrk** [comment]
There's now an updated version of this PR in https://github.com/jupyter/jupyter_console/pull/196

**Comment by MSeal** [comment]
Closing as the updated PR was merged a year ago

**Pull request closed without merging**
